FROM ubuntu AS builder

RUN apt update && apt install -y git && \
    git clone https://github.com/commnerd/maikr.git /tmp/maikr

FROM node AS builder2

RUN bash -c 'npm install -g npm@8.10.0 @angular/cli'

COPY --from=builder /tmp/maikr/ui /srv/ui
COPY --from=builder /tmp/maikr/lib /srv/lib
WORKDIR /srv/ui

RUN ng build

FROM nginx

COPY --from=builder2 /srv/ui/dist/maikr/* /usr/share/nginx/html