version: "3"
services:
  ui:
    build: ui/docker
    image: maikr/ui
    volumes:
      - ./lib:/maikr/lib
      - ./ui:/maikr/ui
    ports:
      - ${UI_PORT:-8080}:4200

  api:
    build: api/docker
    image: maikr/api
    volumes:
      - ./lib:/maikr/lib
      - ./api:/maikr/api
    ports:
      - ${API_PORT:-8081}:80
    command: [ "bash", "-c", "yarn && yarn dev" ]

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8082}:80
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
