version: "3"
services:
  ui:
    build: ui/docker
    image: maikr/ui
    volumes:
      - ./ui:/ui
    ports:
      - ${PORT:-80}:4200

  api:
    build: api/docker
    image: maikr/api
    volumes:
      - ./api:/api
    ports:
      - ${PORT:-81}:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
