local_resource(
    name='ui',
    serve_cmd='cd ../../ui/web && npm install && ng serve',
    allow_parallel=True,
    links = [
        link('http://localhost:4200', 'UI')
    ]
)

local_resource(
    name='lib-enums-builder',
    serve_cmd='cd ../../lib/enums && npm install && ./node_modules/webpack/bin/webpack.js watch',
    allow_parallel=True
)

local_resource(
    name='lib-interfaces-builder',
    serve_cmd='cd ../../lib/interfaces && npm install && ./node_modules/webpack/bin/webpack.js watch',
    allow_parallel=True
)

local_resource(
    name='lib-models-builder',
    serve_cmd='cd ../../lib/models && npm install && ./node_modules/webpack/bin/webpack.js watch --stats-error-details',
    allow_parallel=True
)