load('ext://uibutton', 'cmd_button', 'location', 'text_input', 'bool_input')
trigger_mode(TRIGGER_MODE_MANUAL)

def dc():
    docker_compose("../../docker-compose.yaml")
    for container in ['mongodb', 'mongo-express', 'srv', 'ui']:
        dc_resource(
            container,
            auto_init=False if container == 'mongo-express' else True,
            labels = ['docker-compose']
        )

    for container in ['srv', 'ui']:
        cmd_button(
            name='build-prod-container-{container}'.format(container=container),
            resource=container,
            text='Build Prod Container',
            argv=[
                '/bin/bash',
                '-c',
                'cd ../../tools/docker/{container} && docker build -t commnerd/maikr-{container} -f Dockerfile.prod .'.format(container=container)
            ]
        )
dc()

def helm_chart():
    k8s_yaml(helm('../helm-chart', name='maikr', set=['ingress.enabled=true']))
    for container in ['maikr', 'maikr-mongo', 'maikr-ui', 'maikr-srv']:
        k8s_resource(
            container,
            labels = ['kubernetes']
        )
