local_resource(
    name='ui',
    serve_cmd='cd ../../ui/web && npm install && ng serve',
    allow_parallel=True,
    links = [
        link('http://localhost:4200', 'UI')
    ]
)

local_resource(
    name='lib-enums-builder',
    serve_cmd='cd ../../lib/enums && npm install && webpack watch',
    allow_parallel=True
)