.DEFAULT: help
CURRENT_DEV_CHAIN = "v0.1.x"

.PHONY: env-help
env-help:
	@echo ""
	@echo "subcommands:"
	@echo "  help    - This list of help commands"
	@echo "  deploy  - Deploy to production"

.PHONY: deploy
deploy:
	@echo "Hello World"