CURRENT_DEV_CHAIN = "v0.1.x"

.PHONY: help
help:
	@echo ""
	@echo "subcommands:"
	@echo "  help           - this list of help commands"
	@echo "  down           - Spin down development environment"
	@echo "  restart        - Restart dev environment"
	@echo "  up             - Spin up development environment"
	@echo "  git-submodules - Install git submodules (dependency)"

.PHONY: down
down:
	@docker-compose down

.PHONY: restart
restart: down up

.PHONY: up
up: git-submodules
	@docker-compose up -d --build

.PHONY: git-submodules
git-submodules:
	@git submodule update --init
	@git submodule foreach --recursive git checkout $(CURRENT_DEV_CHAIN) && git pull