FROM ubuntu AS builder

RUN apt update && apt install -y git && \
    git clone https://github.com/commnerd/maikr.git /tmp/maikr

FROM node

ENV MONGO_USER  user
ENV MONGO_PASS  pass
ENV MONGO_URL   mongodb
ENV MONGO_TABLE admin

EXPOSE 3000

COPY --from=builder /tmp/maikr/srv /srv/srv
COPY --from=builder /tmp/maikr/lib /srv/lib
WORKDIR /srv/srv

ENTRYPOINT [ "bash", "-c", "npm install && npm run serve" ]
