apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "maikr.fullname" . }}-mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: {{ include "maikr.fullname" . }}-mongodb-statefulset
  serviceName: "{{ include "maikr.fullname" . }}-mongodb-service"
  replicas: {{ .Values.mongodb.replicas }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ include "maikr.fullname" . }}-mongodb-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 27017
          name: db
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi