name: Docker Image CI

on:
  push:
    branches: ["v0.2.x"]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for UI on DockerHub
        id: meta-ui
        uses: docker/metadata-action@v4
        with:
          images: commnerd/maikr-ui

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v3
        with:
          file: tools/docker/ui/Dockerfile.prod
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          push: true
          tags: ${{ steps.meta-ui.outputs.tags }}
          labels: ${{ steps.meta-ui.outputs.labels }}

      - name: Extract metadata (tags, labels) for Server on DockerHub
        id: meta-srv
        uses: docker/metadata-action@v4
        with:
          images: commnerd/maikr-srv

      - name: Build and push Server Docker image
        uses: docker/build-push-action@v3
        with:
          file: tools/docker/srv/Dockerfile.prod
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          push: true
          tags: ${{ steps.meta-srv.outputs.tags }}
          labels: ${{ steps.meta-srv.outputs.labels }}
